version: 2
jobs:
  build:
    docker:
      - image: rust:1.33.0

    steps:
      - checkout

      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version

      - run:
          name: Build all targets
          command: cargo build --all --all-targets
